// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SX400.Api.Data;

#nullable disable

namespace SX400.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SX400.Api.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2026, 1, 15),
                            Summary = "Warm",
                            TemperatureC = 22
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2026, 1, 16),
                            Summary = "Freezing",
                            TemperatureC = -5
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2026, 1, 17),
                            Summary = "Hot",
                            TemperatureC = 35
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2026, 1, 18),
                            Summary = "Cool",
                            TemperatureC = 10
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2026, 1, 19),
                            Summary = "Balmy",
                            TemperatureC = 28
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
